-- ============================================================
-- 3Wi PMO Suite - Migration 0003: Clients
--
-- Adds a Client layer between Tenants and Projects.
--
-- Hierarchy:
--   3Wi (platform)  ->  Tenant (consulting firm, e.g. IBS)
--                       ->  Client (firm's customer, e.g. Hempire-EC)
--                           ->  Project (e.g. Sunshines)
--
-- A Tenant manages many Clients. A Client owns many Projects.
-- Brand colours can be overridden per-Client for white-label per-customer.
--
-- Backward compatibility:
--   `projects.client_id` is NULLABLE so existing rows are not orphaned.
--   New code paths should set client_id when creating a project.
--   Optional backfill query at the bottom for tenants who want all
--   pre-existing projects rolled up under a single "Direct" client.
-- ============================================================

-- ---- Clients table ----

CREATE TABLE IF NOT EXISTS clients (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id             UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name                  TEXT NOT NULL,
  slug                  TEXT NOT NULL,
  legal_name            TEXT,
  registration_number   TEXT,
  vat_number            TEXT,
  brand_color_primary   TEXT,
  brand_color_secondary TEXT,
  brand_color_accent    TEXT,
  logo_url              TEXT,
  primary_contact_name  TEXT,
  primary_contact_email TEXT,
  status                TEXT NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'paused', 'archived')),
  notes                 TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, slug)
);

CREATE INDEX IF NOT EXISTS clients_tenant_idx ON clients(tenant_id);

-- ---- Add client_id to projects ----

ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES clients(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS projects_client_idx ON projects(client_id);

-- ---- RLS for clients ----
-- Same tenant-isolation pattern as the rest of the schema.
-- Relies on `current_tenant()` from migration 0002.

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS clients_tenant_isolation ON clients;
CREATE POLICY clients_tenant_isolation ON clients
  USING (tenant_id = current_tenant())
  WITH CHECK (tenant_id = current_tenant());

-- ---- Seed data: IBS tenant + Hempire-EC client + Sunshines project link ----
-- Skipped here. Apply via apps/api/src/services/seed.ts so it stays in sync
-- with bcrypt password hashes and tenant ids generated by Prisma.

-- ---- Optional one-shot backfill (run manually if desired) ----
-- For tenants that have existing projects and want them rolled up under a
-- single "Direct" client (rather than orphaned), run this:
--
--   INSERT INTO clients (tenant_id, name, slug, status)
--     SELECT id, 'Direct', 'direct', 'active'
--     FROM tenants
--     WHERE NOT EXISTS (SELECT 1 FROM clients WHERE clients.tenant_id = tenants.id)
--   ON CONFLICT (tenant_id, slug) DO NOTHING;
--
--   UPDATE projects SET client_id = c.id
--     FROM clients c
--     WHERE projects.tenant_id = c.tenant_id
--       AND c.slug = 'direct'
--       AND projects.client_id IS NULL;
--
-- Don't auto-run the backfill; it's a deliberate decision per tenant.

-- end of 0003_clients.sql
